// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbiuvnbsqveukduykqtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaXV2bmJzcXZldWtkdXlrcXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzA1NDYsImV4cCI6MjA2MzE0NjU0Nn0.aNtzuwKAQ-ewi67JQuUH3vAq6_6x-5rU_Pq_QGMPuh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);